PRINT_STRING:
    MOVER R1, [R0]
    JZ EXIT_PRINT_STRING
    OUT_CHAR R1
    ADD R0, #1
    JMP PRINT_STRING
EXIT_PRINT_STRING: RET

COMPARE_STRINGS:
    MOVER R3, [R1]
    MOVER R4, [R2]
    CMP R3, R4
    JNZ NOT_EQUAL
    CMP R3, #0
    JZ EQUAL
    ADD R1, #1
    ADD R2, #1
    JMP COMPARE_STRINGS
NOT_EQUAL:
    MOVER R0, #0
    RET
EQUAL:
    MOVER R0, #1
    RET